### PR TITLE
Update people_sans_members.json

### PR DESCRIPTION
**Pull request by aazaff**
Added Andrew Zaffos to tech team

### CODE REVIEW

**Comment by jczaplew** [comment]
@cambro please review

**Comment by jczaplew** [comment]
Waiting on contribution

**Comment by aazaff** [comment]
I can't believe I'm still waiting on this.

**Comment by aazaff** [comment]
Also added new link to paleobiologyDatabase.R repository to apps section. Please consult.

**Comment by jczaplew** [comment]
The new app was taken care of in 4b8264546b88586347c529a61177cac1288b3a44 by @cambro, which is a great example of which file should be edited.

**Pull request merged**
